### ISSUE TITLE
Plug-in Name issue?

### ISSUE THREAD

**Issue by andrew-burgher** [bstillitano/homebridge-actron-neo#2] opened 2023-09-10 08:19 UTC
Using default plugin name setting on install.

HB log has following Warning after first restart:
"A platform configured a new accessory under the plugin name 'homebridge-actron-neo'. However no loaded plugin could be found for the name!"

And after 2nd restart, the following Info:
"When searching for the associated plugin of the accessory 'homebridge-actron-neo' it seems like the plugin name changed from 'homebridge-actron-neo' to '@bstillitano/homebridge-actron-neo'. Plugin association is now being transformed!"

Cached accessory appears to be loading OK however.

**Comment by bstillitano** [comment] 2023-09-13 21:26
Thanks @andrew-burgher for reporting this. I'll spin up a clean docker instance of homebridge and see if I can repro it. 

I believe that the renaming of the repo npm package should have resolved this but will confirm.

**Comment by bstillitano** [comment] 2023-09-14 04:27
Closing as resolved. The issue is no longer occurring from what I can tell. Please reopen this issue if it continues occurring after deleting the plugin and migrating to the new one.

**Closed by bstillitano** 2023-09-14 04:27 UTC
